# Site settings
email: diego.bianchetti@gmail.com 
baseurl: ""
paginate: 5
paginate_path: "/blog/page-:num"
google_analytics: 

# SEO settings
title: TortugaVoladora
description: Vuela vuela tortuguita con alas!
url: "tortugavoladora.life"
twitter_username: 
default_img: 

# Profile settings
name: Diego Bianchetti
profile_img: 
profile: Nomade de bicicleta pelo mundo!
social:
 github: gituhub.com/diegobianchetti
 instagram: instagram.com/diegobianchetti
 facebook: facebook.com/bianchettidiego

# Build settings
exclude: ["_screenshots", "Gemfile", "Gemfile.lock", "LICENSE.txt", "README.md"]
markdown: kramdown
permalink: /:year/:month/:day/:title/

# Sass
sass:
  style: compressed

# Gems
gems: [jekyll-paginate, jekyll-sitemap, octopress-autoprefixer]
